### ISSUE TITLE
Error parsing floats with really small exponents

### ISSUE THREAD

**Issue by enekoatxa** [orangeduck/BVHView#4]
Hello, I have been trying the web version to visualize some BVH files, and I think i found a small bug when the parser tries to parse floats with exponents that have 2 digits in them. I append an image that shows the error.
![error](https://github.com/orangeduck/BVHView/assets/43878591/62eb9814-c928-49a4-b7e3-5141383a6b53)

Even though I am not sure that having 2 digits is the problem, I think that is the case, because the line the error occurs in (shown in the next image) fails with the e-40 exponent, and if I remove the 0 to leave a e-4 exponent, the error goes away, and catches the next 2 digit exponent.
![error2](https://github.com/orangeduck/BVHView/assets/43878591/45e99e61-4fd2-442f-a5cc-9a568833a347)

Thanks in advance.

**Comment by orangeduck** [comment]
Thanks again for the big report @enekoatxa - can you upload the file causing issues so I can take a look? I suspect the problem is the number is too small to be represented as a float. I can potentially switch the parser to parse doubles and then convert to floats. As a work-around you might be able to get it to work by converting to floats before you write out the bvh file you are exporting (assuming it is your own script doing the export).

**Comment by enekoatxa** [comment]
Oh, you may be completely right. I deleted the file, sorry, but I generated a new one, that also fails. This one fails at line 541:287, with a number with exponent e-39.

[randomGenerator.zip](https://github.com/orangeduck/BVHView/files/15483148/randomGenerator.zip)

Meanwhile, I will change my script to export in a better format (I overlooked the unnecessary precision of the output that I generate). 
Thank you so much!

**Comment by orangeduck** [comment]
I've pushed up a fix for this here:

https://github.com/orangeduck/BVHView/commit/800e4035a988249ca17c63a882c0db119b4210a7

Now it can open that file. As mentioned in the other thread I will update the pre-compiled windows binaries and web demo next week :)

Thanks,

Dan

**Comment by enekoatxa** [comment]
Thank you so much, again!
